In [8]:
import numpy as np
import strawberryfields as sf
from strawberryfields import ops, RemoteEngine
import time

In [9]:
Us = np.load('Us_spectra.npy')
U = Us[1]  #C2H4
print(np.real(U))

[[-0.53491056  0.83826709  0.10356058 -0.02131166]
 [-0.67951341 -0.49990836  0.53698308  0.00152286]
 [-0.42950848 -0.17320834 -0.70628009  0.53543419]
 [ 0.26010513  0.13190447  0.44954733  0.84430665]]


In [10]:
prog = sf.Program(8)
with prog.context as q:
    # Initial squeezed states
    # Allowed values are r=1.0 or r=0.0
    ops.S2gate(1.0) | (q[0], q[4])
    ops.S2gate(1.0) | (q[1], q[5])
    ops.S2gate(1.0) | (q[2], q[6])
    ops.S2gate(1.0) | (q[3], q[7])
    
    # Interferometer on the signal modes (0-3)
    ops.Interferometer(U) | (q[0], q[1], q[2], q[3])
    ops.Interferometer(U) | (q[4], q[5], q[6], q[7])
    
    ops.MeasureFock() | q
    


In [11]:
eng = RemoteEngine('X8_01')
results = eng.run(prog, shots=400000)
samples = results.samples

2020-10-26 15:00:02,706 - INFO - The device spec X8_01 has been successfully retrieved.
2020-10-26 15:00:02,712 - INFO - Compiling program for device X8_01 using compiler Xunitary.
2020-10-26 15:00:03,222 - INFO - Job 271c83a4-2792-4ae1-b940-55c1fd0e88a3 was successfully submitted.
2020-10-26 15:00:31,385 - INFO - The remote job 271c83a4-2792-4ae1-b940-55c1fd0e88a3 has been completed.


In [12]:
samples[:100]

array([[0, 0, 0, 2, 2, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 1, 2, 1],
       [0, 0, 0, 0, 0, 0, 2, 0],
       [0, 1, 0, 0, 0, 2, 0, 2],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 2, 0, 1, 0, 1],
       [0, 2, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 2, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 3, 0, 1, 0, 0],
       [0, 2, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 4, 0, 0, 2, 3],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 3, 0],
       [0, 1, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0],
       [0, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 2, 0, 0, 1, 0, 0],
       [1, 1, 0, 1, 0, 1, 0, 1],
       [0, 2, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 1, 0],
       [3, 0, 1, 1, 1, 0, 0, 1],
       [2, 0, 0, 1, 1, 0, 1, 0],
       [0,

In [13]:
from strawberryfields.apps import vibronic, plot
import plotly
samples = [list(s) for s in samples]
w = [2979, 1580, 1286, 977]
wp = [2828, 1398, 1227, 855]
energies = vibronic.energies(samples, w, wp)

In [14]:
plot.spectrum(energies, xmin=-6000, xmax=6000)